/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_opengles_color_NativeColorRenderer */

#ifndef YINGKE_SIMPLECODEC_NATIVE_YUV2RGB_H
#define YINGKE_SIMPLECODEC_NATIVE_YUV2RGB_H
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL yuv2rgb(JNIEnv *, jclass , jstring, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
