/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yingke_audio_faac_encoder_encoder_FaacUtil */

//#ifndef _Included_com_yingke_audio_faac_encoder_encoder_FaacUtil
//#define _Included_com_yingke_audio_faac_encoder_encoder_FaacUtil

extern "C"
JNIEXPORT jlongArray JNICALL
Java_com_yingke_audio_faac_encoder_encoder_FaacUtil_faacOpen(JNIEnv *env, jclass thiz,
                                                             jint sample_rate, jint channels);
extern "C"
JNIEXPORT jint JNICALL
Java_com_yingke_audio_faac_encoder_encoder_FaacUtil_faacEncode(JNIEnv *env, jclass thiz,
                                                               jshortArray pcm_buffer, jint samples,
                                                               jbyteArray aac_buffer);
extern "C"
JNIEXPORT void JNICALL
Java_com_yingke_audio_faac_encoder_encoder_FaacUtil_faacClose(JNIEnv *env, jclass thiz) ;