/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yingke_audio_mp3lame_encoder_encoder_LameUtil */

#ifndef _Included_com_yingke_audio_mp3lame_encoder_encoder_LameUtil
#define _Included_com_yingke_audio_mp3lame_encoder_encoder_LameUtil
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
