/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yingke_audio_mp3lame_encoder_encoder_LameUtil_Companion */

#ifndef _Included_com_yingke_audio_mp3lame_encoder_encoder_LameUtil_Companion
#define _Included_com_yingke_audio_mp3lame_encoder_encoder_LameUtil_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yingke_audio_mp3lame_encoder_encoder_LameUtil_Companion
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_yingke_audio_mp3lame_encoder_encoder_LameUtil_00024Companion_init
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_yingke_audio_mp3lame_encoder_encoder_LameUtil_Companion
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_yingke_audio_mp3lame_encoder_encoder_LameUtil_00024Companion_encode
  (JNIEnv *, jobject, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_yingke_audio_mp3lame_encoder_encoder_LameUtil_Companion
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_yingke_audio_mp3lame_encoder_encoder_LameUtil_00024Companion_flush
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_yingke_audio_mp3lame_encoder_encoder_LameUtil_Companion
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yingke_audio_mp3lame_encoder_encoder_LameUtil_00024Companion_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
